[tool.black]
line-length = 120
include = 'smartserving'
extend-exclude = '/.*/'
skip-magic-trailing-comma = true
preview = true
enable-unstable-feature = ['hug_parens_with_braces_and_square_brackets', 'docstring_check_for_newline']